table DimCustomer
	lineageTag: eb927d86-399d-4ec5-a154-7b672aa31ebb

	column CustomerID
		dataType: string
		lineageTag: 2cbb64c3-6f41-4228-8119-9f0e2b1502d4
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column customer_name
		dataType: string
		lineageTag: aab02754-d319-423e-859b-e5d01f649af8
		summarizeBy: none
		sourceColumn: customer_name

		annotation SummarizationSetBy = Automatic

	partition DimCustomer = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\pramo\Downloads\customer_data.csv"),[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_id", type text}, {"customer_name", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"customer_id", "CustomerID"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

